# Generated by Django 5.1.4 on 2024-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('species', models.CharField(default='All pets', max_length=15)),
                ('gender', models.CharField(default='All', max_length=10)),
                ('age', models.CharField(default='All', max_length=15)),
                ('breed', models.CharField(default='Unknown breed', max_length=100)),
                ('photo', models.ImageField(upload_to='animals/')),
                ('description', models.TextField(blank=True)),
                ('found_home', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('neutered', models.BooleanField(default=False)),
                ('vaccinated', models.BooleanField(default=False)),
            ],
        ),
    ]
