# Generated by Django 5.1.4 on 2025-01-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('species', models.CharField(default='All pets', max_length=15)),
                ('gender', models.CharField(default='All', max_length=10)),
                ('age', models.CharField(default='All', max_length=15)),
                ('breed', models.CharField(default='Unknown breed', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('found_home', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('neutered', models.BooleanField(default=False)),
                ('vaccinated', models.BooleanField(default=False)),
                ('uploaded_images', models.ImageField(upload_to='animals/')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='animals/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animals.animal')),
            ],
        ),
    ]
