export interface IAnimalList {
    id: 1,
    name: "Max",
    species: "Dogs",
    gender: "Male",
    age: "1-2 y.o.",
    breed: "Purebred",
    photo: "http://example.com/media/animals/max.jpg",
    description: "A friendly dog looking for a home.",
    found_home: false,
    location: "Kyiv, Ukraine",
    date_added: "2025-01-08",
    neutered: true,
    vaccinated: true,
};
